### ISSUE TITLE
Checklist of things needed for Process Daemons

### ISSUE THREAD

**Issue by Herxity** [Herxity/SWE2024#16]
Development Stage
  Platform:
  - [x] Start and Kill Containers
  - [x] Port assignment
  - [x] Hardware limit enforcement
  - [x] Get containers
  - [x] Forward JSON to containers
  - [x] Internal timer for automatic self-destruction as well as container killing
  - [x] Request more resources
  
  Eval: *most basic functions come from Platform Process Daemons*
  - [x] Load testing data
  - [x] Perform tests
  - [x] Track metrics during inference(could be done as background process)
  - [x] Report findings to database
  - [x] Automatically move to next model in queue if queued

Integration Stage:
Platform:
- [x] Link to billing system
