### ISSUE TITLE
Checklist of things needed for Manager

### ISSUE THREAD

**Issue by Herxity** [Herxity/SWE2024#19]
Development Stage:
- [x] Spawn Process.
- [x] Respect resource allocation when spawning.
- [x] Initialize Container.
- [x] Proper deletion process for the container if shut down manually or internally(via timer).
- [x] Request resource message in (does not go in queue).
- [x] Resource allocation system.
- [x] Distinguish between O and G blocks for user.
- [x] Take away O blocks repeatedly in atomic units via lottery when assigning G blocks to another user.  Users with more O blocks have more risk of losing them. This is the most 'fair' and forces all users to risk getting O blocks taken away equally.
- [x] Allocate/Deallocate Ports
- [x] Reroute API calls

Low Priority
- [ ] Message validation for Queue(tbd).
- [ ] Orphan Reaping.
- [ ] Periodic Port Mapping Checking
